alertmanager-ud-rule.yml
---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hackathon-alert
  namespace: eda-hackathon-0001
spec:
  groups:
  - name: hackathon-rule
    rules:
    - alert: HackathonAlert
      for: 1m
      expr: kube_job_status_failed{job_name="prometheus-hackathon-app"} > 0
      labels:
        severity: warning
      annotations:
        message: This is an example alert for the hackathon.


hackathon-alert-routing.yml
---

apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: example-routing
  namespace: eda-hackathon-0001
spec:
  route:
    receiver: receiver0001
    groupBy: [job]
  receivers:
  - name: receiver0001
    webhookConfigs:
    - url: https://example.org/post


hackathon-job.yaml
---

apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-hackathon-app
  namespace: eda-hackathon-0001
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 6
  template:
    metadata:
      name: prometheus-hackathon-app
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl", "-e", "die 'This job will fail!'"]
      restartPolicy: OnFailure
